In [2]:
import numpy as np

# Desafio 1: Arrays Sequenciais
# Valores pares entre 50 e 100
valores_pares = np.arange(50, 101, 2)
print(f"Valores pares: {valores_pares}")

# Múltiplos de 5 entre 5 e 55
multiplos_cinco = np.arange(5, 56, 5)
print(f"Múltiplos de 5: {multiplos_cinco}")

# Desafio 2: Distribuição Uniforme
# 10 valores uniformemente distribuídos entre 100 e 200
uniformes = np.linspace(100, 200, 10)
print(f"Valores uniformemente distribuídos: {uniformes}")

# Desafio 3: Dados Aleatórios
# Matriz 5x5 com valores aleatórios entre 1 e 50
matriz_aleatoria = np.random.randint(1, 51, size=(5, 5))
print(f"Matriz 5x5 aleatória: {matriz_aleatoria}")

# Array de 15 valores aleatórios, fixando a seed
np.random.seed(42)
valores_aleatorios_fixos = np.random.randint(1, 20, 15)
print(f"Valores aleatórios fixos: {valores_aleatorios_fixos}")

# Desafio 5: Permutação
# Embaralhar letras do alfabeto
alfabeto = ['a', 'b', 'c', 'd', 'e']
np.random.shuffle(alfabeto)
print(f"Letras embaralhadas: {alfabeto}")

# Permutar números de 1 a 15
numeros = np.arange(1, 16)
numeros_permutados = np.random.permutation(numeros)
print(f"Números originais: {numeros}")
print(f"Números permutados: {numeros_permutados}")


Valores pares: [ 50  52  54  56  58  60  62  64  66  68  70  72  74  76  78  80  82  84
  86  88  90  92  94  96  98 100]
Múltiplos de 5: [ 5 10 15 20 25 30 35 40 45 50 55]
Valores uniformemente distribuídos: [100.         111.11111111 122.22222222 133.33333333 144.44444444
 155.55555556 166.66666667 177.77777778 188.88888889 200.        ]
Matriz 5x5 aleatória: [[ 7 21  9 39 18]
 [ 4 25 14 50  9]
 [26  2 20 28 47]
 [ 7 44  8 47 35]
 [14 17 36 50 40]]
Valores aleatórios fixos: [ 7 15 11  8  7 19 11 11  4  8  3  2 12  6  2]
Letras embaralhadas: ['c', 'b', 'e', 'a', 'd']
Números originais: [ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]
Números permutados: [ 2 14  5 11 15  8  7  4  3  1  9 12 13  6 10]
