In [44]:
import numpy as np

# Manipulação do shape de arrays e matrizes
vendas = np.array([100, 200, 150, 170])

vendas_loja_1 = np.array([[759, 450],
                          [350, 299]])

vendas_loja_2 = np.array([[250, 298],
                          [355, 295],
                          [775, 135]]) #3x2 ->2x3

vendas_loja_3 = np.array([[852, 199],
                          [123, 345],
                          [465, 678],
                          [345,644]]) # 4x2 ->2x4 -> 8x1

print("Shape array vendas:", vendas.shape)
print("Shape matriz vendas_loja_1:", vendas_loja_1.shape)
print("Shape matriz vendas_loja_2:", vendas_loja_2.shape)
print("Shape matriz vendas_loja_3:", vendas_loja_3.shape)

# Reshape - Alterar o shape(formato de um array ou matriz)
print(f'Shape array vendas: {vendas.reshape(2,2)}')
print(f'Shape vendas_loja_2 = {vendas_loja_2.reshape(2,3)}')
print(f'Shape vendas_loja_3 = {vendas_loja_3.reshape(8,1)}')

# Transposição - (inverter as dimensões de um array)
nova_vendas_loja_2_transposta = vendas_loja_2.T
print(nova_vendas_loja_2_transposta)


Shape array vendas: (4,)
Shape matriz vendas_loja_1: (2, 2)
Shape matriz vendas_loja_2: (3, 2)
Shape matriz vendas_loja_3: (4, 2)
Shape array vendas: [[100 200]
 [150 170]]
Shape vendas_loja_2 = [[250 298 355]
 [295 775 135]]
Shape vendas_loja_3 = [[852]
 [199]
 [123]
 [345]
 [465]
 [678]
 [345]
 [644]]
[[250 355 775]
 [298 295 135]]
