In [4]:
# Desafio 1 - A partir do array abaixo de 30 pesos diferentes, gere 3 arrays a partir de uma janela deslizante de 10 itens, coloque este resultado em uma variável chamada faixas_pesos e imprima o resultado com um laço for

import numpy as np

np.random.seed(1337)
pesos = np.random.randint(50,120,30) # Array de pesos, mínimo 50, máximo 120, total de 30 pesos
# [73, 111,  89,  89,  59,  56, 104,  73,  74,  51, 77,  56,  72, 116, 115, 110,  69, 101, 107, 117, 70, 58, 111,  59, 118,  56, 118,  96,  70,  68]
janela = 10

faixas_pesos = [pesos[i:i+janela] for i in range(0,len(pesos) - janela + 1, 10 )]
for faixa in faixas_pesos:
    print(faixa)

# A partir da variável faixas_pesos, faça duas list comprehension para resolver os seguintes problemas:
# Encontre o desvio padrão de cada faixa de peso, guarde isso numa variável chamada desvio_padrao_pesos e imprima o resultado na tela
desvio_padrao_pesos = [np.std(faixa) for faixa in faixas_pesos]
print(desvio_padrao_pesos)

# Encontre o valor máximo entre cada faixa de peso, guarde isso numa variável chamada pesos_máximo e imprima o resultado na tela
pesos_maximos = [np.max(faixa) for faixa in faixas_pesos]
print(pesos_maximos)

[ 73 111  89  89  59  56 104  73  74  51]
[ 77  56  72 116 115 110  69 101 107 117]
[ 70  58 111  59 118  56 118  96  70  68]
[19.096858380372414, 21.840329667841555, 24.274266209300745]
[111, 117, 118]
