In [34]:
import numpy as np

# Ordenação de arrays
valores = np.array([32, 10, 5, 80, 90, 30])
# Modificar array original
valores.sort() # Crescente
valores = valores[::-1] # Decrescente

# Ordenar, sem modificar array original
idades = np.array([25, 30, 20, 40, 35])
idades_ord_cres = np.sort(idades)
idades_ord_descre = np.sort(idades)[::-1]
idades_ord_descre

matriz = np.array([[5, 7, 6],
                   [2, 10, 9],
                   [1, 8, 3]])

matriz_ord_linhas = np.sort(matriz,axis=1) # linha
matriz_ord_linhas_desc = np.flip(matriz_ord_linhas,axis=1)

matriz_ord_cols = np.sort(matriz,axis=0) # Coluna
matriz_ord_cols_desc = np.flip(matriz_ord_cols,axis=0)

print(f'Matriz ord por linhas: {matriz_ord_linhas}')
print(f'Matriz ord por linhas desc: {matriz_ord_linhas_desc}')

print(f'Matriz ord por colunas: {matriz_ord_cols}')
print(f'Matriz ord por colunas desc: {matriz_ord_cols_desc}')


# Como retornar apenas o índice de um array de forma ordenada
pontos = np.array([100, 90, 80, 95, 85])
indices_pontos_ord = np.argsort(pontos)
indices_pontos_ord

Matriz ord por linhas: [[ 5  6  7]
 [ 2  9 10]
 [ 1  3  8]]
Matriz ord por linhas desc: [[ 7  6  5]
 [10  9  2]
 [ 8  3  1]]
Matriz ord por colunas: [[ 1  7  3]
 [ 2  8  6]
 [ 5 10  9]]
Matriz ord por colunas desc: [[ 5 10  9]
 [ 2  8  6]
 [ 1  7  3]]


array([2, 4, 1, 3, 0], dtype=int64)