In [12]:
import numpy as np
# Desafio 1: Dado o array de notas, ordene-o em ordem decrescente.
notas = np.array([85, 90, 78, 88, 76, 95])
notas_ordenadas = np.sort(notas)[::-1]
print(notas_ordenadas)

# Desafio 2: Crie uma matriz 3x3 com valores aleatórios entre 1 e 10. Ordene essa matriz pelo eixo das colunas.
np.random.seed(30)
matriz = np.random.randint(1, 11, (3, 3))
print(np.sort(matriz, axis=0))

# Desafio 3: Dado o array de alturas , use argsort() para descobrir a posição da pessoa mais alta e da pessoa mais baixa.
alturas = np.array([1.75, 1.82, 1.60, 1.90, 1.65])
ordem_alturas = np.argsort(alturas)
print("Posição da pessoa mais baixa:", ordem_alturas[0])
print("Posição da pessoa mais alta:", ordem_alturas[-1])



[95 90 88 85 78 76]
[[ 2  3  5]
 [ 6  4  6]
 [ 8  6 10]]
Posição da pessoa mais baixa: 2
Posição da pessoa mais alta: 3
