In [ ]:
# Operações matemáticas avançadas de um jeito fácil!
import numpy as np

# Exponenciação x³ 5³
print(np.power(5,3)) # valor individuais
numeros = np.array([1,2,3]) # para arrays
print(np.power(numeros,2))

# Logarítimo natural
# Para que potência eu preciso elevar o número e(aprox 2.71) para obter esse número?
print(np.log(7))
numeros = np.array([1,2,3,7]) # para arrays
print(np.log(numeros))

# Raíz Quadrada (qual número, multiplicado a sí mesmo, resultado em determinado valor)
print(np.sqrt(16))
numeros = np.array([1, 4, 9, 16])
print(np.sqrt(numeros))

# Desvio Padrão (qual distante da média os valores estão)
dados = np.array([50, 50, 47, 53, 52]) 
print(np.std(dados)) #pode variar tanto para  +2.05 ou -2.05



125
[1 4 9]
1.9459101490553132
[0.         0.69314718 1.09861229 1.94591015]
4.0
[1. 2. 3. 4.]
2.0591260281974
