In [90]:
# Leitura e Criação de arquivos com numpy
import numpy as np

# Ler um arquivo
dados = np.loadtxt('./dados.csv',delimiter=',')
vendas = np.loadtxt('./vendas.csv',delimiter=',',skiprows=1)
print(vendas)

# Criar
array_exemplo = np.array([[10, 11.234567, 12], [13, 14.63, 15], [16.555, 17, 18]])
np.savetxt('./padrao.csv',array_exemplo,delimiter=',')
np.savetxt('./inteiros.csv',array_exemplo,delimiter=',',fmt='%d')
np.savetxt('./decimais_2casas_dec.csv',array_exemplo,delimiter=',',fmt='%.2f')
np.savetxt('./decimais_3casas_dec.csv',array_exemplo,delimiter=',',fmt='%.6f')

# Código do desafio(pontuações de jogadores) dentro do arquivo 'resultado_desafio.ipynb'






[[  1. 100.   2.]
 [  2. 400.   5.]
 [  3. 200.   7.]]
