Operações matemáticas com Arrays

In [1]:
import numpy as np

pesos_1 = np.array([10, 20, 30])
pesos_2 = np.array([40, 50, 60])

# soma
print(pesos_1 + pesos_2)

# subtração
print(pesos_1 - pesos_2)

# multiplicação
print(pesos_1 * pesos_2)

# divisão
print(pesos_1 / pesos_2)

# multiplicação
print(pesos_1 * pesos_2)

[50 70 90]
[-30 -30 -30]
[ 400 1000 1800]
[0.25 0.4  0.5 ]
[ 400 1000 1800]
